// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8MXB8dQEjSzVl2ocFw_c-NcNl6JP5CDU',
    appId: '1:943573241074:web:9c3507fc2cd6325b71946b',
    messagingSenderId: '943573241074',
    projectId: 'speak-master-8b755',
    authDomain: 'speak-master-8b755.firebaseapp.com',
    storageBucket: 'speak-master-8b755.firebasestorage.app',
    measurementId: 'G-C9HL9G2CKZ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb_HjsMUtpWLpIgyUgP0LXCPisONNkMz4',
    appId: '1:943573241074:ios:269bc551bbc452ad71946b',
    messagingSenderId: '943573241074',
    projectId: 'speak-master-8b755',
    storageBucket: 'speak-master-8b755.firebasestorage.app',
    iosBundleId: 'com.example.communicate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb_HjsMUtpWLpIgyUgP0LXCPisONNkMz4',
    appId: '1:943573241074:ios:269bc551bbc452ad71946b',
    messagingSenderId: '943573241074',
    projectId: 'speak-master-8b755',
    storageBucket: 'speak-master-8b755.firebasestorage.app',
    iosBundleId: 'com.example.communicate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8MXB8dQEjSzVl2ocFw_c-NcNl6JP5CDU',
    appId: '1:943573241074:web:b077c4fc2be0cc3d71946b',
    messagingSenderId: '943573241074',
    projectId: 'speak-master-8b755',
    authDomain: 'speak-master-8b755.firebaseapp.com',
    storageBucket: 'speak-master-8b755.firebasestorage.app',
    measurementId: 'G-RVG2546B92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWtWmYuQ8jAU8PvQ61xjyCWiNkAa06f4A',
    appId: '1:943573241074:android:af2c97330782050271946b',
    messagingSenderId: '943573241074',
    projectId: 'speak-master-8b755',
    storageBucket: 'speak-master-8b755.firebasestorage.app',
  );

}