final List<Map<String, String>> sentenceBank = [
  {'english': 'How are you?', 'hindi': 'आप कैसे हैं?'},
  {'english': 'Where are you going?', 'hindi': 'आप कहाँ जा रहे हैं?'},
  {'english': 'What is your name?', 'hindi': 'आपका नाम क्या है?'},
  {'english': 'I love to learn languages.', 'hindi': 'मुझे भाषाएँ सीखना पसंद है।'},
  {'english': 'Can you help me?', 'hindi': 'क्या आप मेरी मदद कर सकते हैं?'},
  {'english': 'This is a beautiful day.', 'hindi': 'यह एक सुंदर दिन है।'},
  {'english': 'I am hungry.', 'hindi': 'मुझे भूख लगी है।'},
  {'english': 'Please sit down.', 'hindi': 'कृपया बैठ जाओ।'},
  {'english': 'Where is the nearest hospital?', 'hindi': 'सबसे नजदीकी अस्पताल कहाँ है?'},
  {'english': 'I am learning Flutter.', 'hindi': 'मैं फ्लटर सीख रहा हूँ।'},
  {'english': 'What time is it?', 'hindi': 'समय क्या हुआ है?'},
  {'english': 'I like reading books.', 'hindi': 'मुझे किताबें पढ़ना पसंद है।'},
  {'english': 'She is my best friend.', 'hindi': 'वह मेरी सबसे अच्छी दोस्त है।'}, 
  {'english': 'I live in Mumbai.', 'hindi': 'मैं मुंबई में रहता हूँ।'},
  {'english': 'Can I ask you a question?', 'hindi': 'क्या मैं आपसे एक सवाल पूछ सकता हूँ?'},
  {'english': 'Where do you work?', 'hindi': 'आप कहाँ काम करते हैं?'},
  {'english': 'I have two brothers.', 'hindi': 'मेरे दो भाई हैं।'},
  {'english': 'The weather is nice today.', 'hindi': 'आज मौसम अच्छा है।'},
  {'english': 'I want to travel the world.', 'hindi': 'मैं दुनिया घूमना चाहता हूँ।'},
  {'english': 'Please open the window.', 'hindi': 'कृपया खिड़की खोलो।'},
  {'english': 'How much does this cost?', 'hindi': 'यह कितना खर्च करता है?'},
  {'english': 'I am feeling tired.', 'hindi': 'मैं थका हुआ महसूस कर रहा हूँ।'},
  {'english': 'She is a good teacher.', 'hindi': 'वह एक अच्छी शिक्षिका है।'},
  {'english': 'I like to play football.', 'hindi': 'मुझे फुटबॉल खेलना पसंद है।'},
  {'english': 'Can you please repeat?', 'hindi': 'क्या आप कृपया दोहरा सकते हैं?'},
  {'english': 'I will call you later.', 'hindi': 'मैं आपको बाद में कॉल करूँगा।'},
  {'english': 'Where is the market?', 'hindi': 'बाजार कहाँ है?'},
  {'english': 'I enjoy cooking.', 'hindi': 'मुझे खाना बनाना पसंद है।'},
  {'english': 'Do you like music?', 'hindi': 'क्या आपको संगीत पसंद है?'},
  {'english': 'I am going to school.', 'hindi': 'मैं स्कूल जा रहा हूँ।'},
  {'english': 'What did you say?', 'hindi': 'आपने क्या कहा?'},
  {'english': 'I need some water.', 'hindi': 'मुझे थोड़ा पानी चाहिए।'},
  {'english': 'This is my house.', 'hindi': 'यह मेरा घर है।'},
  {'english': 'Where can I find a taxi?', 'hindi': 'मुझे टैक्सी कहाँ मिलेगी?'},
  {'english': 'I love watching movies.', 'hindi': 'मुझे फिल्में देखना पसंद है।'},
  {'english': 'He is very kind.', 'hindi': 'वह बहुत दयालु है।'},
  {'english': 'Please write your name.', 'hindi': 'कृपया अपना नाम लिखें।'},
  {'english': 'I have a dog.', 'hindi': 'मेरे पास एक कुत्ता है।'},
  {'english': 'How old are you?', 'hindi': 'आप कितने साल के हैं?'},
  {'english': 'I want to learn Hindi.', 'hindi': 'मैं हिंदी सीखना चाहता हूँ।'},
  {'english': 'Can you help me find it?', 'hindi': 'क्या आप मुझे इसे ढूंढ़ने में मदद कर सकते हैं?'},
  {'english': 'What is your favorite color?', 'hindi': 'आपका पसंदीदा रंग कौन सा है?'},
  {'english': 'I am feeling happy.', 'hindi': 'मैं खुश महसूस कर रहा हूँ।'},
  {'english': 'She is very beautiful.', 'hindi': 'वह बहुत खूबसूरत है।'},
  {'english': 'Where did you go yesterday?', 'hindi': 'आप कल कहाँ गए थे?'},
  {'english': 'Please turn off the light.', 'hindi': 'कृपया बत्ती बंद कर दो।'},
  {'english': 'I want to drink tea.', 'hindi': 'मैं चाय पीना चाहता हूँ।'},
  {'english': 'Do you like to dance?', 'hindi': 'क्या आपको नाचना पसंद है?'},
  {'english': 'I am studying English.', 'hindi': 'मैं अंग्रेज़ी पढ़ रहा हूँ।'},
  {'english': 'Can you come here?', 'hindi': 'क्या आप यहाँ आ सकते हैं?'},
  {'english': 'I love my family.', 'hindi': 'मुझे अपना परिवार पसंद है।'},
  {'english': 'What is the time now?', 'hindi': 'अभी समय क्या हुआ है?'},
  {'english': 'He is my brother.', 'hindi': 'वह मेरा भाई है।'},
  {'english': 'Please be quiet.', 'hindi': 'कृपया चुप रहो।'},
  {'english': 'I want to buy a gift.', 'hindi': 'मैं एक उपहार खरीदना चाहता हूँ।'},
  {'english': 'Do you have a pen?', 'hindi': 'क्या आपके पास पेन है?'},
  {'english': 'I like swimming.', 'hindi': 'मुझे तैराकी पसंद है।'},
  {'english': 'Where is your school?', 'hindi': 'आपका स्कूल कहाँ है?'},
  {'english': 'She is reading a book.', 'hindi': 'वह एक किताब पढ़ रही है।'},
  {'english': 'Can you drive a car?', 'hindi': 'क्या आप कार चला सकते हैं?'},
  {'english': 'I need to go now.', 'hindi': 'मुझे अब जाना है।'},
  {'english': 'What do you want to eat?', 'hindi': 'आप क्या खाना चाहते हैं?'},
  {'english': 'Please close the door.', 'hindi': 'कृपया दरवाजा बंद करो।'},
  {'english': 'I am going to the market.', 'hindi': 'मैं बाजार जा रहा हूँ।'},
  {'english': 'He is my teacher.', 'hindi': 'वह मेरा शिक्षक है।'},
  {'english': 'Do you like coffee?', 'hindi': 'क्या आपको कॉफी पसंद है?'},
  {'english': 'I am feeling cold.', 'hindi': 'मुझे ठंड लग रही है।'},
  {'english': 'Please help me.', 'hindi': 'कृपया मेरी मदद करें।'},
  {'english': 'She is singing a song.', 'hindi': 'वह एक गीत गा रही है।'},
  {'english': 'I want to visit India.', 'hindi': 'मैं भारत जाना चाहता हूँ।'},
  {'english': 'Can you swim?', 'hindi': 'क्या आप तैर सकते हैं?'},
  {'english': 'I like playing cricket.', 'hindi': 'मुझे क्रिकेट खेलना पसंद है।'},
  {'english': 'Where do you live?', 'hindi': 'आप कहाँ रहते हैं?'},
  {'english': 'Please speak slowly.', 'hindi': 'कृपया धीरे बोलें।'},
  {'english': 'I am happy today.', 'hindi': 'मैं आज खुश हूँ।'},
  {'english': 'She is my sister.', 'hindi': 'वह मेरी बहन है।'},
  {'english': 'Can you open the window?', 'hindi': 'क्या आप खिड़की खोल सकते हैं?'},
  {'english': 'I want to learn new things.', 'hindi': 'मैं नई चीजें सीखना चाहता हूँ।'},
  {'english': 'Do you like to travel?', 'hindi': 'क्या आपको यात्रा करना पसंद है?'},
  {'english': 'I am tired now.', 'hindi': 'मैं अब थका हुआ हूँ।'},
  {'english': 'Please write it down.', 'hindi': 'कृपया इसे लिखें।'},
  {'english': 'She is cooking food.', 'hindi': 'वह खाना बना रही है।'},
  {'english': 'I want to watch TV.', 'hindi': 'मैं टीवी देखना चाहता हूँ।'},
  {'english': 'Can you read this?', 'hindi': 'क्या आप इसे पढ़ सकते हैं?'},
  {'english': 'I like to listen to music.', 'hindi': 'मुझे संगीत सुनना पसंद है।'},
  {'english': 'Where is your house?', 'hindi': 'आपका घर कहाँ है?'},
  {'english': 'Please give me water.', 'hindi': 'कृपया मुझे पानी दें।'},
  {'english': 'I am learning new words.', 'hindi': 'मैं नए शब्द सीख रहा हूँ।'},
  {'english': 'She is wearing a red dress.', 'hindi': 'वह लाल कपड़े पहन रही है।'},
  {'english': 'Can you come tomorrow?', 'hindi': 'क्या आप कल आ सकते हैं?'},
  {'english': 'I want to eat something.', 'hindi': 'मैं कुछ खाना चाहता हूँ।'},
  {'english': 'Please take a seat.', 'hindi': 'कृपया बैठ जाएं।'},
  {'english': 'He is playing the guitar.', 'hindi': 'वह गिटार बजा रहा है।'},
  {'english': 'I like to write stories.', 'hindi': 'मुझे कहानियाँ लिखना पसंद है।'},
  {'english': 'Where can I buy this?', 'hindi': 'मैं इसे कहाँ खरीद सकता हूँ?'},
  {'english': 'Please call me later.', 'hindi': 'कृपया मुझे बाद में कॉल करें।'}, 
  {'english': 'I am going home.', 'hindi': 'मैं घर जा रहा हूँ।'},
  {'english': 'She is my mother.', 'hindi': 'वह मेरी माँ है।'},
  {'english': 'Can you help me with this?', 'hindi': 'क्या आप मेरी इसमें मदद कर सकते हैं?'},
  {'english': 'I want to sleep now.', 'hindi': 'मैं अब सोना चाहता हूँ।'},
  {'english': 'Please stop talking.', 'hindi': 'कृपया बात करना बंद करें।'},
  {'english': 'He is reading the newspaper.', 'hindi': 'वह अखबार पढ़ रहा है।'},
  {'english': 'I like to draw pictures.', 'hindi': 'मुझे चित्र बनाना पसंद है।'},
  {'english': 'Where is the bank?', 'hindi': 'बैंक कहाँ है?'},
  {'english': 'Please help me find my keys.', 'hindi': 'कृपया मेरी चाबियाँ ढूंढ़ने में मदद करें।'},
];