
final List<Map<String, dynamic>> my_verbs = [
    {"id": "1", "v2": "Go", "hindi": "जाना", "v2_past": "Went", "v3_past": "Gone", "v4_ing_form": "Going"},
    {"id": "2", "v2": "Eat", "hindi": "खाना", "v2_past": "Ate", "v3_past": "Eaten", "v4_ing_form": "Eating"},
    {"id": "3", "v2": "Sleep", "hindi": "सोना", "v2_past": "Slept", "v3_past": "Slept", "v4_ing_form": "Sleeping"},
    {"id": "4", "v2": "Drink", "hindi": "पीना", "v2_past": "Drank", "v3_past": "Drunk", "v4_ing_form": "Drinking"},
    {"id": "5", "v2": "Come", "hindi": "आना", "v2_past": "Came", "v3_past": "Come", "v4_ing_form": "Coming"},
    {"id": "6", "v2": "Read", "hindi": "पढ़ना", "v2_past": "Read", "v3_past": "Read", "v4_ing_form": "Reading"},
    {"id": "7", "v2": "Write", "hindi": "लिखना", "v2_past": "Wrote", "v3_past": "Written", "v4_ing_form": "Writing"},
    {"id": "8", "v2": "Speak", "hindi": "बोलना", "v2_past": "Spoke", "v3_past": "Spoken", "v4_ing_form": "Speaking"},
    {"id": "9", "v2": "Listen", "hindi": "सुनना", "v2_past": "Listened", "v3_past": "Listened", "v4_ing_form": "Listening"},
    {"id": "10", "v2": "See", "hindi": "देखना", "v2_past": "Saw", "v3_past": "Seen", "v4_ing_form": "Seeing"},
    {"id": "11", "v2": "Walk", "hindi": "चलना", "v2_past": "Walked", "v3_past": "Walked", "v4_ing_form": "Walking"},
    {"id": "12", "v2": "Run", "hindi": "दौड़ना", "v2_past": "Ran", "v3_past": "Run", "v4_ing_form": "Running"},
    {"id": "13", "v2": "Play", "hindi": "खेलना", "v2_past": "Played", "v3_past": "Played", "v4_ing_form": "Playing"},
    {"id": "14", "v2": "Work", "hindi": "काम करना", "v2_past": "Worked", "v3_past": "Worked", "v4_ing_form": "Working"},
    {"id": "15", "v2": "Study", "hindi": "पढ़ाई करना", "v2_past": "Studied", "v3_past": "Studied", "v4_ing_form": "Studying"},
    {"id": "16", "v2": "Teach", "hindi": "पढ़ाना", "v2_past": "Taught", "v3_past": "Taught", "v4_ing_form": "Teaching"},
    {"id": "17", "v2": "Learn", "hindi": "सीखना", "v2_past": "Learnt / Learned", "v3_past": "Learnt / Learned", "v4_ing_form": "Learning"},
    {"id": "18", "v2": "Understand", "hindi": "समझना", "v2_past": "Understood", "v3_past": "Understood", "v4_ing_form": "Understanding"},
    {"id": "19", "v2": "Give", "hindi": "देना", "v2_past": "Gave", "v3_past": "Given", "v4_ing_form": "Giving"},
    {"id": "20", "v2": "Take", "hindi": "लेना", "v2_past": "Took", "v3_past": "Taken", "v4_ing_form": "Taking"},
    {"id": "21", "v2": "Make", "hindi": "बनाना", "v2_past": "Made", "v3_past": "Made", "v4_ing_form": "Making"},
    {"id": "22", "v2": "Do", "hindi": "करना", "v2_past": "Did", "v3_past": "Done", "v4_ing_form": "Doing"},
    {"id": "23", "v2": "Buy", "hindi": "खरीदना", "v2_past": "Bought", "v3_past": "Bought", "v4_ing_form": "Buying"},
    {"id": "24", "v2": "Sell", "hindi": "बेचना", "v2_past": "Sold", "v3_past": "Sold", "v4_ing_form": "Selling"},
    {"id": "25", "v2": "Live", "hindi": "जीना / रहना", "v2_past": "Lived", "v3_past": "Lived", "v4_ing_form": "Living"},
    {"id": "26", "v2": "Die", "hindi": "मरना", "v2_past": "Died", "v3_past": "Died", "v4_ing_form": "Dying"},
    {"id": "27", "v2": "Love", "hindi": "प्यार करना", "v2_past": "Loved", "v3_past": "Loved", "v4_ing_form": "Loving"},
    {"id": "28", "v2": "Hate", "hindi": "नफरत करना", "v2_past": "Hated", "v3_past": "Hated", "v4_ing_form": "Hating"},
    {"id": "29", "v2": "Help", "hindi": "मदद करना", "v2_past": "Helped", "v3_past": "Helped", "v4_ing_form": "Helping"},
    {"id": "30", "v2": "Thank", "hindi": "धन्यवाद करना", "v2_past": "Thanked", "v3_past": "Thanked", "v4_ing_form": "Thanking"},
    {"id": "31", "v2": "Ask", "hindi": "पूछना", "v2_past": "Asked", "v3_past": "Asked", "v4_ing_form": "Asking"},
    {"id": "32", "v2": "Answer", "hindi": "जवाब देना", "v2_past": "Answered", "v3_past": "Answered", "v4_ing_form": "Answering"},
    {"id": "33", "v2": "Call", "hindi": "बुलाना", "v2_past": "Called", "v3_past": "Called", "v4_ing_form": "Calling"},
    {"id": "34", "v2": "Send", "hindi": "भेजना", "v2_past": "Sent", "v3_past": "Sent", "v4_ing_form": "Sending"},
    {"id": "35", "v2": "Receive", "hindi": "प्राप्त करना", "v2_past": "Received", "v3_past": "Received", "v4_ing_form": "Receiving"},
    {"id": "36", "v2": "Open", "hindi": "खोलना", "v2_past": "Opened", "v3_past": "Opened", "v4_ing_form": "Opening"},
    {"id": "37", "v2": "Close", "hindi": "बंद करना", "v2_past": "Closed", "v3_past": "Closed", "v4_ing_form": "Closing"},
    {"id": "38", "v2": "Start", "hindi": "शुरू करना", "v2_past": "Started", "v3_past": "Started", "v4_ing_form": "Starting"},
    {"id": "39", "v2": "Finish", "hindi": "खत्म करना", "v2_past": "Finished", "v3_past": "Finished", "v4_ing_form": "Finishing"},
    {"id": "40", "v2": "Wait", "hindi": "इंतजार करना", "v2_past": "Waited", "v3_past": "Waited", "v4_ing_form": "Waiting"},
    {"id": "41", "v2": "Bring", "hindi": "लाना", "v2_past": "Brought", "v3_past": "Brought", "v4_ing_form": "Bringing"},
    {"id": "42", "v2": "Find", "hindi": "खोजना", "v2_past": "Found", "v3_past": "Found", "v4_ing_form": "Finding"},
    {"id": "43", "v2": "Lose", "hindi": "खोना", "v2_past": "Lost", "v3_past": "Lost", "v4_ing_form": "Losing"},
    {"id": "44", "v2": "Win", "hindi": "जीतना", "v2_past": "Won", "v3_past": "Won", "v4_ing_form": "Winning"},
    {"id": "45", "v2": "Build", "hindi": "बनाना / निर्माण करना", "v2_past": "Built", "v3_past": "Built", "v4_ing_form": "Building"},
    {"id": "46", "v2": "Break", "hindi": "तोड़ना", "v2_past": "Broke", "v3_past": "Broken", "v4_ing_form": "Breaking"},
    {"id": "47", "v2": "Catch", "hindi": "पकड़ना", "v2_past": "Caught", "v3_past": "Caught", "v4_ing_form": "Catching"},
    {"id": "48", "v2": "Throw", "hindi": "फेंकना", "v2_past": "Threw", "v3_past": "Thrown", "v4_ing_form": "Throwing"},
    {"id": "49", "v2": "Cut", "hindi": "काटना", "v2_past": "Cut", "v3_past": "Cut", "v4_ing_form": "Cutting"},
    {"id": "50", "v2": "Sing", "hindi": "गाना", "v2_past": "Sang", "v3_past": "Sung", "v4_ing_form": "Singing"},
    {"id": "51", "v2": "Drive", "hindi": "गाड़ी चलाना", "v2_past": "Drove", "v3_past": "Driven", "v4_ing_form": "Driving"},
    {"id": "52", "v2": "Ride", "hindi": "सवारी करना", "v2_past": "Rode", "v3_past": "Ridden", "v4_ing_form": "Riding"},
    {"id": "53", "v2": "Know", "hindi": "जानना", "v2_past": "Knew", "v3_past": "Known", "v4_ing_form": "Knowing"},
    {"id": "54", "v2": "Grow", "hindi": "उगाना / बढ़ना", "v2_past": "Grew", "v3_past": "Grown", "v4_ing_form": "Growing"},
    {"id": "55", "v2": "Fly", "hindi": "उड़ना", "v2_past": "Flew", "v3_past": "Flown", "v4_ing_form": "Flying"},
    {"id": "56", "v2": "Draw", "hindi": "चित्र बनाना", "v2_past": "Drew", "v3_past": "Drawn", "v4_ing_form": "Drawing"},
    {"id": "57", "v2": "Show", "hindi": "दिखाना", "v2_past": "Showed", "v3_past": "Shown", "v4_ing_form": "Showing"},
    {"id": "58", "v2": "Fall", "hindi": "गिरना", "v2_past": "Fell", "v3_past": "Fallen", "v4_ing_form": "Falling"},
    {"id": "59", "v2": "Rise", "hindi": "उठना / उगना", "v2_past": "Rose", "v3_past": "Risen", "v4_ing_form": "Rising"},
    {"id": "60", "v2": "Swim", "hindi": "तैरना", "v2_past": "Swam", "v3_past": "Swum", "v4_ing_form": "Swimming"},
    {"id": "61", "v2": "Begin", "hindi": "शुरू करना", "v2_past": "Began", "v3_past": "Begun", "v4_ing_form": "Beginning"},
    {"id": "62", "v2": "Become", "hindi": "बनना", "v2_past": "Became", "v3_past": "Become", "v4_ing_form": "Becoming"},
    {"id": "63", "v2": "Bring", "hindi": "लाना", "v2_past": "Brought", "v3_past": "Brought", "v4_ing_form": "Bringing"},
    {"id": "64", "v2": "Choose", "hindi": "चुनना", "v2_past": "Chose", "v3_past": "Chosen", "v4_ing_form": "Choosing"},
    {"id": "65", "v2": "Deal", "hindi": "व्यवहार करना", "v2_past": "Dealt", "v3_past": "Dealt", "v4_ing_form": "Dealing"},
    {"id": "66", "v2": "Dream", "hindi": "सपना देखना", "v2_past": "Dreamt / Dreamed", "v3_past": "Dreamt / Dreamed", "v4_ing_form": "Dreaming"},
    {"id": "67", "v2": "Fight", "hindi": "लड़ना", "v2_past": "Fought", "v3_past": "Fought", "v4_ing_form": "Fighting"},
    {"id": "68", "v2": "Forget", "hindi": "भूलना", "v2_past": "Forgot", "v3_past": "Forgotten", "v4_ing_form": "Forgetting"},
    {"id": "69", "v2": "Get", "hindi": "प्राप्त करना", "v2_past": "Got", "v3_past": "Got / Gotten", "v4_ing_form": "Getting"},
    {"id": "70", "v2": "Hear", "hindi": "सुनना", "v2_past": "Heard", "v3_past": "Heard", "v4_ing_form": "Hearing"},
    {"id": "71", "v2": "Hold", "hindi": "पकड़ना", "v2_past": "Held", "v3_past": "Held", "v4_ing_form": "Holding"},
    {"id": "72", "v2": "Keep", "hindi": "रखना", "v2_past": "Kept", "v3_past": "Kept", "v4_ing_form": "Keeping"},
    {"id": "73", "v2": "Leave", "hindi": "छोड़ना", "v2_past": "Left", "v3_past": "Left", "v4_ing_form": "Leaving"},
    {"id": "74", "v2": "Meet", "hindi": "मिलना", "v2_past": "Met", "v3_past": "Met", "v4_ing_form": "Meeting"},
    {"id": "75", "v2": "Pay", "hindi": "भुगतान करना", "v2_past": "Paid", "v3_past": "Paid", "v4_ing_form": "Paying"},
    {"id": "76", "v2": "Put", "hindi": "रखना", "v2_past": "Put", "v3_past": "Put", "v4_ing_form": "Putting"},
    {"id": "77", "v2": "Say", "hindi": "कहना", "v2_past": "Said", "v3_past": "Said", "v4_ing_form": "Saying"},
    {"id": "78", "v2": "Sit", "hindi": "बैठना", "v2_past": "Sat", "v3_past": "Sat", "v4_ing_form": "Sitting"},
    {"id": "79", "v2": "Stand", "hindi": "खड़ा होना", "v2_past": "Stood", "v3_past": "Stood", "v4_ing_form": "Standing"},
    {"id": "80", "v2": "Tell", "hindi": "बताना", "v2_past": "Told", "v3_past": "Told", "v4_ing_form": "Telling"},
    {"id": "81", "v2": "Think", "hindi": "सोचना", "v2_past": "Thought", "v3_past": "Thought", "v4_ing_form": "Thinking"},
    {"id": "82", "v2": "Understand", "hindi": "समझना", "v2_past": "Understood", "v3_past": "Understood", "v4_ing_form": "Understanding"},
    {"id": "83", "v2": "Wake", "hindi": "जागना", "v2_past": "Woke", "v3_past": "Woken", "v4_ing_form": "Waking"},
    {"id": "84", "v2": "Wear", "hindi": "पहनना", "v2_past": "Wore", "v3_past": "Worn", "v4_ing_form": "Wearing"},
    {"id": "85", "v2": "Win", "hindi": "जीतना", "v2_past": "Won", "v3_past": "Won", "v4_ing_form": "Winning"},
    {"id": "86", "v2": "Abide", "hindi": "पालन करना", "v2_past": "Abode / Abided", "v3_past": "Abode / Abided", "v4_ing_form": "Abiding"},
    {"id": "87", "v2": "Arise", "hindi": "उठना", "v2_past": "Arose", "v3_past": "Arisen", "v4_ing_form": "Arising"},
    {"id": "88", "v2": "Awake", "hindi": "जागना", "v2_past": "Awoke / Awaked", "v3_past": "Awoken / Awaked", "v4_ing_form": "Awaking"},
    {"id": "89", "v2": "Be", "hindi": "होना", "v2_past": "Was / Were", "v3_past": "Been", "v4_ing_form": "Being"},
    {"id": "90", "v2": "Bear", "hindi": "सहना / जन्म देना", "v2_past": "Bore", "v3_past": "Born / Borne", "v4_ing_form": "Bearing"},
    {"id": "91", "v2": "Beat", "hindi": "पीटना", "v2_past": "Beat", "v3_past": "Beaten", "v4_ing_form": "Beating"},
    {"id": "92", "v2": "Bend", "hindi": "मोड़ना", "v2_past": "Bent", "v3_past": "Bent", "v4_ing_form": "Bending"},
    {"id": "93", "v2": "Bet", "hindi": "शर्त लगाना", "v2_past": "Bet", "v3_past": "Bet", "v4_ing_form": "Betting"},
    {"id": "94", "v2": "Bind", "hindi": "बांधना", "v2_past": "Bound", "v3_past": "Bound", "v4_ing_form": "Binding"},
    {"id": "95", "v2": "Bite", "hindi": "काटना", "v2_past": "Bit", "v3_past": "Bitten", "v4_ing_form": "Biting"},
    {"id": "96", "v2": "Bleed", "hindi": "खून बहना", "v2_past": "Bled", "v3_past": "Bled", "v4_ing_form": "Bleeding"},
    {"id": "97", "v2": "Blow", "hindi": "फूँकना", "v2_past": "Blew", "v3_past": "Blown", "v4_ing_form": "Blowing"},
    {"id": "98", "v2": "Burst", "hindi": "फटना", "v2_past": "Burst", "v3_past": "Burst", "v4_ing_form": "Bursting"},
    {"id": "99", "v2": "Cast", "hindi": "फेंकना", "v2_past": "Cast", "v3_past": "Cast", "v4_ing_form": "Casting"},
    {"id": "100", "v2": "Cling", "hindi": "चिपकना", "v2_past": "Clung", "v3_past": "Clung", "v4_ing_form": "Clinging"},
    {"id": "101", "v2": "Cost", "hindi": "कीमत होना", "v2_past": "Cost", "v3_past": "Cost", "v4_ing_form": "Costing"},
    {"id": "102", "v2": "Creep", "hindi": "रेंगना", "v2_past": "Crept", "v3_past": "Crept", "v4_ing_form": "Creeping"},
    {"id": "103", "v2": "Dig", "hindi": "खोदना", "v2_past": "Dug", "v3_past": "Dug", "v4_ing_form": "Digging"},
    {"id": "104", "v2": "Draw", "hindi": "खींचना", "v2_past": "Drew", "v3_past": "Drawn", "v4_ing_form": "Drawing"},
    {"id": "105", "v2": "Feed", "hindi": "खिलाना", "v2_past": "Fed", "v3_past": "Fed", "v4_ing_form": "Feeding"},
    {"id": "106", "v2": "Feel", "hindi": "महसूस करना", "v2_past": "Felt", "v3_past": "Felt", "v4_ing_form": "Feeling"},
    {"id": "107", "v2": "Flee", "hindi": "भागना", "v2_past": "Fled", "v3_past": "Fled", "v4_ing_form": "Fleeing"},
    {"id": "108", "v2": "Fling", "hindi": "फेंकना", "v2_past": "Flung", "v3_past": "Flung", "v4_ing_form": "Flinging"},
    {"id": "109", "v2": "Forbid", "hindi": "मना करना", "v2_past": "Forbade", "v3_past": "Forbidden", "v4_ing_form": "Forbidding"},
    {"id": "110", "v2": "Forgive", "hindi": "माफ़ करना", "v2_past": "Forgave", "v3_past": "Forgiven", "v4_ing_form": "Forgiving"},
    {"id": "111", "v2": "Freeze", "hindi": "जमना", "v2_past": "Froze", "v3_past": "Frozen", "v4_ing_form": "Freezing"},
    {"id": "112", "v2": "Grind", "hindi": "पीसना", "v2_past": "Ground", "v3_past": "Ground", "v4_ing_form": "Grinding"},
    {"id": "113", "v2": "Hang", "hindi": "लटकाना", "v2_past": "Hung", "v3_past": "Hung", "v4_ing_form": "Hanging"},
    {"id": "114", "v2": "Hide", "hindi": "छिपाना", "v2_past": "Hid", "v3_past": "Hidden", "v4_ing_form": "Hiding"},
    {"id": "115", "v2": "Hit", "hindi": "मारना", "v2_past": "Hit", "v3_past": "Hit", "v4_ing_form": "Hitting"},
    {"id": "116", "v2": "Hurt", "hindi": "चोट पहुँचाना", "v2_past": "Hurt", "v3_past": "Hurt", "v4_ing_form": "Hurting"},
    {"id": "117", "v2": "Lay", "hindi": "लेटना / रखना", "v2_past": "Lay", "v3_past": "Lain", "v4_ing_form": "Laying"},
    {"id": "118", "v2": "Lead", "hindi": "नेतृत्व करना", "v2_past": "Led", "v3_past": "Led", "v4_ing_form": "Leading"},
    {"id": "119", "v2": "Lend", "hindi": "उधार देना", "v2_past": "Lent", "v3_past": "Lent", "v4_ing_form": "Lending"},
    {"id": "120", "v2": "Light", "hindi": "प्रकाश करना", "v2_past": "Lit / Lighted", "v3_past": "Lit / Lighted", "v4_ing_form": "Lighting"},
    {"id": "121", "v2": "Mean", "hindi": "मतलब होना", "v2_past": "Meant", "v3_past": "Meant", "v4_ing_form": "Meaning"},
    {"id": "122", "v2": "Overcome", "hindi": "पार पाना", "v2_past": "Overcame", "v3_past": "Overcome", "v4_ing_form": "Overcoming"},
    {"id": "123", "v2": "Prove", "hindi": "साबित करना", "v2_past": "Proved", "v3_past": "Proven / Proved", "v4_ing_form": "Proving"},
    {"id": "124", "v2": "Quit", "hindi": "छोड़ना", "v2_past": "Quit", "v3_past": "Quit", "v4_ing_form": "Quitting"},
    {"id": "125", "v2": "Ride", "hindi": "सवारी करना", "v2_past": "Rode", "v3_past": "Ridden", "v4_ing_form": "Riding"},
    {"id": "126", "v2": "Ring", "hindi": "बजाना (घंटी)", "v2_past": "Rang", "v3_past": "Rung", "v4_ing_form": "Ringing"},
    {"id": "127", "v2": "Seek", "hindi": "खोज करना", "v2_past": "Sought", "v3_past": "Sought", "v4_ing_form": "Seeking"},
    {"id": "128", "v2": "Shine", "hindi": "चमकना", "v2_past": "Shone", "v3_past": "Shone", "v4_ing_form": "Shining"},
    {"id": "129", "v2": "Shoot", "hindi": "गोली मारना", "v2_past": "Shot", "v3_past": "Shot", "v4_ing_form": "Shooting"},
    {"id": "130", "v2": "Shut", "hindi": "बंद करना", "v2_past": "Shut", "v3_past": "Shut", "v4_ing_form": "Shutting"},
    {"id": "131", "v2": "Sling", "hindi": "फेंकना", "v2_past": "Slung", "v3_past": "Slung", "v4_ing_form": "Slinging"},
    {"id": "132", "v2": "Slit", "hindi": "काटना / चीरना", "v2_past": "Slit", "v3_past": "Slit", "v4_ing_form": "Slitting"},
    {"id": "133", "v2": "Sow", "hindi": "बोना", "v2_past": "Sowed", "v3_past": "Sown / Sowed", "v4_ing_form": "Sowing"},
    {"id": "134", "v2": "Spell", "hindi": "वर्तनी करना", "v2_past": "Spelt / Spelled", "v3_past": "Spelt / Spelled", "v4_ing_form": "Spelling"},
    {"id": "135", "v2": "Spend", "hindi": "खर्च करना", "v2_past": "Spent", "v3_past": "Spent", "v4_ing_form": "Spending"},
    {"id": "136", "v2": "Spit", "hindi": "थूकना", "v2_past": "Spat / Spit", "v3_past": "Spat / Spit", "v4_ing_form": "Spitting"},
    {"id": "137", "v2": "Spread", "hindi": "फैलाना", "v2_past": "Spread", "v3_past": "Spread", "v4_ing_form": "Spreading"},
    {"id": "138", "v2": "Spring", "hindi": "कूदना / उछलना", "v2_past": "Sprang", "v3_past": "Sprung", "v4_ing_form": "Springing"},
    {"id": "139", "v2": "Sting", "hindi": "डंक मारना", "v2_past": "Stung", "v3_past": "Stung", "v4_ing_form": "Stinging"},
    {"id": "140", "v2": "Stink", "hindi": "बदबू आना", "v2_past": "Stank / Stunk", "v3_past": "Stunk", "v4_ing_form": "Stinking"},
    {"id": "141", "v2": "Strive", "hindi": "प्रयास करना", "v2_past": "Strove", "v3_past": "Striven", "v4_ing_form": "Striving"},
    {"id": "142", "v2": "Strike", "hindi": "टकराना / हड़ताल करना", "v2_past": "Struck", "v3_past": "Struck / Stricken", "v4_ing_form": "Striking"},
    {"id": "143", "v2": "Swear", "hindi": "कसम खाना", "v2_past": "Swore", "v3_past": "Sworn", "v4_ing_form": "Swearing"},
    {"id": "144", "v2": "Sweep", "hindi": "झाड़ू लगाना", "v2_past": "Swept", "v3_past": "Swept", "v4_ing_form": "Sweeping"},
    {"id": "145", "v2": "Swell", "hindi": "सूजना", "v2_past": "Swelled", "v3_past": "Swollen / Swelled", "v4_ing_form": "Swelling"},
    {"id": "146", "v2": "Tear", "hindi": "फाड़ना", "v2_past": "Tore", "v3_past": "Torn", "v4_ing_form": "Tearing"},
    {"id": "147", "v2": "Thrive", "hindi": "फलना-फूलना", "v2_past": "Thrived / Throve", "v3_past": "Thrived / Thriven", "v4_ing_form": "Thriving"},
    {"id": "148", "v2": "Tread", "hindi": "चलना / कुचलना", "v2_past": "Trod", "v3_past": "Trodden / Trod", "v4_ing_form": "Treading"},
    {"id": "149", "v2": "Undergo", "hindi": "गुजरना / अनुभव करना", "v2_past": "Underwent", "v3_past": "Undergone", "v4_ing_form": "Undergoing"},
    {"id": "150", "v2": "Upset", "hindi": "परेशान करना", "v2_past": "Upset", "v3_past": "Upset", "v4_ing_form": "Upsetting"},
    {"id": "151", "v2": "Weave", "hindi": "बुनना", "v2_past": "Wove / Weaved", "v3_past": "Woven / Weaved", "v4_ing_form": "Weaving"},
    {"id": "152", "v2": "Weep", "hindi": "रोना", "v2_past": "Wept", "v3_past": "Wept", "v4_ing_form": "Weeping"},
    {"id": "153", "v2": "Withdraw", "hindi": "निकालना / पीछे हटना", "v2_past": "Withdrew", "v3_past": "Withdrawn", "v4_ing_form": "Withdrawing"},
    {"id": "154", "v2": "Wring", "hindi": "निचोड़ना", "v2_past": "Wrung", "v3_past": "Wrung", "v4_ing_form": "Wringing"},
    {"id": "155", "v2": "Write", "hindi": "लिखना", "v2_past": "Wrote", "v3_past": "Written", "v4_ing_form": "Writing"},
    {"id": "156", "v2": "Admit", "hindi": "दाखिल करना / स्वीकार करना", "v2_past": "Admitted", "v3_past": "Admitted", "v4_ing_form": "Admitting"},
    {"id": "157", "v2": "Agree", "hindi": "सहमत होना", "v2_past": "Agreed", "v3_past": "Agreed", "v4_ing_form": "Agreeing"},
    {"id": "158", "v2": "Allow", "hindi": "अनुमति देना", "v2_past": "Allowed", "v3_past": "Allowed", "v4_ing_form": "Allowing"},
    {"id": "159", "v2": "Announce", "hindi": "घोषणा करना", "v2_past": "Announced", "v3_past": "Announced", "v4_ing_form": "Announcing"},
    {"id": "160", "v2": "Apologize", "hindi": "माफी मांगना", "v2_past": "Apologized", "v3_past": "Apologized", "v4_ing_form": "Apologizing"},
    {"id": "161", "v2": "Appear", "hindi": "प्रकट होना", "v2_past": "Appeared", "v3_past": "Appeared", "v4_ing_form": "Appearing"},
    {"id": "162", "v2": "Applaud", "hindi": "तालियां बजाना", "v2_past": "Applauded", "v3_past": "Applauded", "v4_ing_form": "Applauding"},
    {"id": "163", "v2": "Arrive", "hindi": "पहुंचना", "v2_past": "Arrived", "v3_past": "Arrived", "v4_ing_form": "Arriving"},
    {"id": "164", "v2": "Attend", "hindi": "उपस्थित होना", "v2_past": "Attended", "v3_past": "Attended", "v4_ing_form": "Attending"},
    {"id": "165", "v2": "Avoid", "hindi": "बचना", "v2_past": "Avoided", "v3_past": "Avoided", "v4_ing_form": "Avoiding"},
    {"id": "166", "v2": "Bake", "hindi": "पकाना (ओवन में)", "v2_past": "Baked", "v3_past": "Baked", "v4_ing_form": "Baking"},
    {"id": "167", "v2": "Believe", "hindi": "विश्वास करना", "v2_past": "Believed", "v3_past": "Believed", "v4_ing_form": "Believing"},
    {"id": "168", "v2": "Belong", "hindi": "संबंध रखना", "v2_past": "Belonged", "v3_past": "Belonged", "v4_ing_form": "Belonging"},
    {"id": "169", "v2": "Blame", "hindi": "दोष देना", "v2_past": "Blamed", "v3_past": "Blamed", "v4_ing_form": "Blaming"},
    {"id": "170", "v2": "Borrow", "hindi": "उधार लेना", "v2_past": "Borrowed", "v3_past": "Borrowed", "v4_ing_form": "Borrowing"},
    {"id": "171", "v2": "Breathe", "hindi": "सांस लेना", "v2_past": "Breathed", "v3_past": "Breathed", "v4_ing_form": "Breathing"},
    {"id": "172", "v2": "Care", "hindi": "परवाह करना", "v2_past": "Cared", "v3_past": "Cared", "v4_ing_form": "Caring"},
    {"id": "173", "v2": "Carry", "hindi": "ले जाना", "v2_past": "Carried", "v3_past": "Carried", "v4_ing_form": "Carrying"},
    {"id": "174", "v2": "Change", "hindi": "बदलना", "v2_past": "Changed", "v3_past": "Changed", "v4_ing_form": "Changing"},
    {"id": "175", "v2": "Clean", "hindi": "साफ करना", "v2_past": "Cleaned", "v3_past": "Cleaned", "v4_ing_form": "Cleaning"},
    {"id": "176", "v2": "Climb", "hindi": "चढ़ना", "v2_past": "Climbed", "v3_past": "Climbed", "v4_ing_form": "Climbing"},
    {"id": "177", "v2": "Collect", "hindi": "इकट्ठा करना", "v2_past": "Collected", "v3_past": "Collected", "v4_ing_form": "Collecting"},
    {"id": "178", "v2": "Compare", "hindi": "तुलना करना", "v2_past": "Compared", "v3_past": "Compared", "v4_ing_form": "Comparing"},
    {"id": "179", "v2": "Complain", "hindi": "शिकायत करना", "v2_past": "Complained", "v3_past": "Complained", "v4_ing_form": "Complaining"},
    {"id": "180", "v2": "Cook", "hindi": "खाना बनाना", "v2_past": "Cooked", "v3_past": "Cooked", "v4_ing_form": "Cooking"},
    {"id": "181", "v2": "Copy", "hindi": "नकल करना", "v2_past": "Copied", "v3_past": "Copied", "v4_ing_form": "Copying"},
    {"id": "182", "v2": "Count", "hindi": "गिनना", "v2_past": "Counted", "v3_past": "Counted", "v4_ing_form": "Counting"},
    {"id": "183", "v2": "Cover", "hindi": "ढकना", "v2_past": "Covered", "v3_past": "Covered", "v4_ing_form": "Covering"},
    {"id": "184", "v2": "Cry", "hindi": "रोना", "v2_past": "Cried", "v3_past": "Cried", "v4_ing_form": "Crying"},
    {"id": "185", "v2": "Dance", "hindi": "नाचना", "v2_past": "Danced", "v3_past": "Danced", "v4_ing_form": "Dancing"},
    {"id": "186", "v2": "Decide", "hindi": "तय करना", "v2_past": "Decided", "v3_past": "Decided", "v4_ing_form": "Deciding"},
    {"id": "187", "v2": "Deliver", "hindi": "वितरित करना", "v2_past": "Delivered", "v3_past": "Delivered", "v4_ing_form": "Delivering"},
    {"id": "188", "v2": "Depend", "hindi": "निर्भर करना", "v2_past": "Depended", "v3_past": "Depended", "v4_ing_form": "Depending"},
    {"id": "189", "v2": "Describe", "hindi": "वर्णन करना", "v2_past": "Described", "v3_past": "Described", "v4_ing_form": "Describing"},
    {"id": "190", "v2": "Destroy", "hindi": "नष्ट करना", "v2_past": "Destroyed", "v3_past": "Destroyed", "v4_ing_form": "Destroying"},
    {"id": "191", "v2": "Develop", "hindi": "विकास करना", "v2_past": "Developed", "v3_past": "Developed", "v4_ing_form": "Developing"},
    {"id": "192", "v2": "Discover", "hindi": "खोज करना", "v2_past": "Discovered", "v3_past": "Discovered", "v4_ing_form": "Discovering"},
    {"id": "193", "v2": "Earn", "hindi": "कमाना", "v2_past": "Earned", "v3_past": "Earned", "v4_ing_form": "Earning"},
    {"id": "194", "v2": "Educate", "hindi": "शिक्षित करना", "v2_past": "Educated", "v3_past": "Educated", "v4_ing_form": "Educating"},
    {"id": "195", "v2": "Enjoy", "hindi": "आनंद लेना", "v2_past": "Enjoyed", "v3_past": "Enjoyed", "v4_ing_form": "Enjoying"},
    {"id": "196", "v2": "Enter", "hindi": "प्रवेश करना", "v2_past": "Entered", "v3_past": "Entered", "v4_ing_form": "Entering"},
    {"id": "197", "v2": "Examine", "hindi": "जांच करना", "v2_past": "Examined", "v3_past": "Examined", "v4_ing_form": "Examining"},
    {"id": "198", "v2": "Explain", "hindi": "समझाना", "v2_past": "Explained", "v3_past": "Explained", "v4_ing_form": "Explaining"},
    {"id": "199", "v2": "Face", "hindi": "सामना करना", "v2_past": "Faced", "v3_past": "Faced", "v4_ing_form": "Facing"},
    {"id": "200", "v2": "Fail", "hindi": "असफल होना", "v2_past": "Failed", "v3_past": "Failed", "v4_ing_form": "Failing"}
];

